name: Cocoapods Trunk Push
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: macos-14

    steps:
      - name: Update Cocoapods Version
        run: sudo gem install cocoapods

      - name: Force Xcode 15
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod trunk push GrowingUtils.podspec --verbose --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.GIOSDK_COCOAPODS_TRUNK_TOKEN }}
