name: Pod Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Pod Lint
        run: pod lib lint GrowingUtils.podspec --allow-warnings --verbose