name: SPM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-iOS:
    runs-on: macos-13

    steps:
      - name: Force Xcode 15
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingUtils-Package -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max' \
          | xcbeautify --renderer github-actions

  build-catalyst:
    runs-on: macos-13

    steps:
      - name: Force Xcode 15
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingUtils-Package -destination 'platform=macOS,variant=Mac Catalyst' \
          | xcbeautify --renderer github-actions

  build-macOS:
    runs-on: macos-13

    steps:
      - name: Force Xcode 15
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingUtils-Package -destination 'platform=macOS' \
          | xcbeautify --renderer github-actions

  build-watchOS:
    runs-on: macos-13

    steps:
      - name: Force Xcode 15
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingUtils-Package -destination 'platform=watchOS' \
          | xcbeautify --renderer github-actions

  build-tvOS:
    runs-on: macos-13

    steps:
      - name: Force Xcode 15
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingUtils-Package -destination 'platform=tvOS' \
          | xcbeautify --renderer github-actions

  build-visionOS:
    runs-on: macos-13

    steps:
      - name: Force Xcode 15
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build -scheme GrowingUtils-Package -destination 'platform=visionOS' \
          | xcbeautify --renderer github-actions